.TH gensio_get_raddr 3 "26 Feb 2019"
.SH NAME
gensio_get_raddr \- Return the remote address for the gensio as a raw
address

.SH SYNOPSIS
.B #include <gensio/gensio.h>
.TP 20
.B int gensio_get_raddr(struct gensio *io, void *addr,
.br
.B                         void *addrlen);
.PP

Return the remote address for the connection.
.I addrlen
must be set to the size of
.I addr
and will be updated to the actual size.  If
.I addrlen
is not large enough to hold the data, the updated
.I addrlen
will be set to the number of bytes required to hold the address,
though the data in the address will be truncated.

The value returned here is connection dependent, and for filter
layers it will pass the call down to the lowest layer to get
the addresses.  Some connection types will not support this.

.SH "RETURN VALUES"
Zero is returned on success, or a gensio error on failure.
.SH "SEE ALSO"
gensio_err(3), gensio(5)
