#cmakedefine USE_PTHREADS
#cmakedefine USE_UUCP_LOCKING
#cmakedefine HAVE_TCPD_H
#cmakedefine HAVE_EPOLL_PWAIT
#cmakedefine01 HAVE_OPENIPMI
#cmakedefine01 HAVE_OPENSSL
#cmakedefine01 HAVE_LIBSCTP
#cmakedefine01 HAVE_SCTP_SENDV
#cmakedefine01 HAVE_UNIX
#cmakedefine01 PYTHON_HAS_POSIX_THREADS
#cmakedefine01 HAVE_GCC_ATOMICS
#cmakedefine01 HAVE_WORKING_PORT0
#cmakedefine HAVE_ISATTY
#cmakedefine HAVE_STRCASECMP
#cmakedefine HAVE_STRNCASECMP
#cmakedefine HAVE_PRCTL
#cmakedefine HAVE_GETRANDOM_FUNC
#cmakedefine HAVE_PTSNAME_R
#cmakedefine HAVE_CFMAKERAW
#cmakedefine HAVE_SIGNALFD
#cmakedefine HAVE_REGEXEC
#cmakedefine HAVE_FNMATCH
#cmakedefine HAVE_AVAHI
#cmakedefine01 USE_FILE_STDIO
#cmakedefine ENABLE_INTERNAL_TRACE
#cmakedefine01 HAVE_DECL_TIOCSRS485
#cmakedefine01 HAVE_STDIO
#cmakedefine01 HAVE_SERIALDEV
#cmakedefine01 HAVE_PTY
