#ifndef GENSIO_CONTROL_H
#define GENSIO_CONTROL_H

#define GENSIO_CONTROL_DEPTH_ALL	-1
#define GENSIO_CONTROL_DEPTH_FIRST	-2

#define GENSIO_CONTROL_GET	true
#define GENSIO_CONTROL_SET	false

#define GENSIO_CONTROL_NODELAY			1u
#define GENSIO_CONTROL_STREAMS			2u
#define GENSIO_CONTROL_SEND_BREAK		3u
#define GENSIO_CONTROL_GET_PEER_CERT_NAME	4u
#define GENSIO_CONTROL_CERT_AUTH		5u
#define GENSIO_CONTROL_USERNAME			6u
#define GENSIO_CONTROL_SERVICE			7u
#define GENSIO_CONTROL_CERT			8u
#define GENSIO_CONTROL_CERT_FINGERPRINT		9u
#define GENSIO_CONTROL_ENVIRONMENT		10u
#define GENSIO_CONTROL_MAX_WRITE_PACKET		11u
#define GENSIO_CONTROL_ARGS			12u
#define GENSIO_CONTROL_EXIT_CODE		13u
#define GENSIO_CONTROL_WAIT_TASK		14u
#define GENSIO_CONTROL_ADD_MCAST		15u
#define GENSIO_CONTROL_DEL_MCAST		16u
#define GENSIO_CONTROL_LADDR			17u
#define GENSIO_CONTROL_LPORT			18u
#define GENSIO_CONTROL_CLOSE_OUTPUT		19u
#define GENSIO_CONTROL_CONNECT_ADDR_STR		20u
#define GENSIO_CONTROL_RADDR			21u
#define GENSIO_CONTROL_RADDR_BIN		22u
#define GENSIO_CONTROL_REMOTE_ID		23u
#define GENSIO_CONTROL_KILL_TASK		24u
#define GENSIO_CONTROL_MCAST_LOOP		25u
#define GENSIO_CONTROL_MCAST_TTL		26u
#define GENSIO_CONTROL_PASSWORD			27u
#define GENSIO_CONTROL_2FA			28u
#define GENSIO_CONTROL_AUX_DATA			29u
#define GENSIO_CONTROL_REM_AUX_DATA		30u
#define GENSIO_CONTROL_IOD			31u
#define GENSIO_CONTROL_EXTRAINFO		32u
#define GENSIO_CONTROL_ENABLE_OOB		33u
#define GENSIO_CONTROL_WIN_SIZE			34u
#define GENSIO_CONTROL_START_DIRECTORY		35u

#define GENSIO_ACC_CONTROL_LADDR	1u
#define GENSIO_ACC_CONTROL_LPORT	2u

/*
 * Get/set the tcpdname option for the gensio dynamically.
 */
#define GENSIO_ACC_CONTROL_TCPDNAME	3u

#endif /* GENSIO_CONTROL_H */
