name: MacOSBuild
on:
  push:
    branches:
      - 'master'
    tags:
      - v*

env:
  INSTALLPREFIX: "_local"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install autotools
        run: |
          brew update
          brew install libtool
          brew install autoconf
          brew install automake
          brew install swig
          brew install openssl
      - name: Configure
        run: |
          mkdir $INSTALLPREFIX
          ./reconf
          ./configure --prefix=$(pwd)/$INSTALLPREFIX/
      - name: Build
        run: |
          make
          make install
          make check