name: WinBuild
on: 
  push:
    branches:
      - 'master'
    tags:
      - v*

env:
  INSTALLPREFIX: "_local"

jobs:
  mingw-build:
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            mingw-w64-${{matrix.env}}-gcc
            mingw-w64-${{matrix.env}}-openssl
            mingw-w64-${{matrix.env}}-python
            mingw-w64-${{matrix.env}}-pcre
            libtool
            autotools
            swig
      - name: MSBuild
        run: |
          ./reconf
          mkdir $INSTALLPREFIX
          ./configure --prefix=$(pwd)/$INSTALLPREFIX/
          make
          make install
          # Unfortunately, on github, test_mdns.py hangs.  I tried
          # it in an AWS windows server 2022 instance and it worked
          # fine, so I don't know what is going on.  The pygensio
          # mdns test works fine.
          #make check
      - name: Upload installed files
        uses: actions/upload-artifact@v3
        with:
          name: gensio-mingw-${{matrix.env}}
          path: ${{ env.INSTALLPREFIX }}/**/*
